import '../globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Import Global Components
import { TopNav } from '@/components/TopNav/TopNav';
import { Footer, FooterBottom } from '@/components/Footer';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="relative min-h-[100vh]">
          <div className="pb-[743px] md:pb-[580px] lg:pb-[370px]">
            <TopNav />
            <main className="mt-1 md:mt-20">{children}</main>
          </div>
          <footer className="absolute w-full bottom-0 -z-10">
            <Footer />
            <FooterBottom />
          </footer>
        </div>
      </body>
    </html>
  );
}
