import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Import Global Components
import { TopNav } from '@/components/TopNav/TopNav';
import { Footer, FooterBottom } from '@/components/Footer';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TopNav />
        {children}
        <Footer />
        <FooterBottom />
      </body>
    </html>
  );
}
